apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: externaltasksblobstore
spec:
  type: bindings.azure.blobstorage
  version: v1
  metadata:
  - name: storageAccount
    value: "taskstracker"
  - name: storageAccessKey
    value: "" 
  - name: container
    value: "externaltaskscontainer"
  - name: decodeBase64
    value: false
  - name: publicAccessLevel
    value: "none"